services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  #pode remover, Docker usa uma rede default automaticamente
    networks:
      - rabbit-net

  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
  #depends_on se removido Pode gerar erro se app subir antes do RabbitMQ
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    container_name: springboot-app
    networks:
      - rabbit-net

networks:
  rabbit-net:
    driver: bridge
