services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit-net

  app:
    build: .
    context: ..  #o contexto de build é a pasta pai da pasta infra/
    dockerfile: infra/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    container_name: springboot-app
    networks:
      - rabbit-net

networks:
  rabbit-net:
    driver: bridge
